spring:
  mail: 
    host: smtp.gmail.com
    port: 587
    username: scirecomunidad@gmail.com
    password: hola1234!
    properties:
        mail:
            smtp:              
                auth: true
                starttls:
                   enable: true

  datasource: 
    url: postgres://kuffuhcdihulja:2e777fda307be7c3ee8eb6180d923c5bea0fa8d7938c61981c3f1f82a1484fcc@ec2-35-169-119-56.compute-1.amazonaws.com:5432/dfiu8stm6jt5nn
    username: kuffuhcdihulja
    password: 2e777fda307be7c3ee8eb6180d923c5bea0fa8d7938c61981c3f1f82a1484fcc
    driver-class-name: org.postgresql.Driver 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect     
  thymeleaf:
    prefix: classpath:/template/
    cache: false 
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        http-only: true
      tracking-modes:
      - cookie